const ERROR = {
  USER_NAME_EXISTS: 'USER_NAME_EXISTS',
  USER_NOT_EXISTS: 'USER_NOT_EXISTS',

  TOKEN_NOT_INCLUDE: 'TOKEN_NOT_INCLUDE',
  TOKEN_EXPIRES: 'TOKEN_EXPIRES',

  TOKEN_NOT_VALID: 'TOKEN_NOT_VALID',

  GALLERY_EXISTS: 'GALLERY_EXISTS',
  GALLERY_NOT_EXISTS: 'GALLERY_NOT_EXISTS',
  GALLERY_NOT_OWNED: 'GALLERY_NOT_OWNED',

  POST_NOT_EXISTS: 'POST_NOT_EXISTS',
  POST_NOW_OWNED: 'POST_NOT_OWNED',

  COMMENT_NOT_EXISTS: 'COMMENT_NOT_EXISTS',
  COMMENT_NOW_OWNED: 'COMMENT_NOT_OWNED',
};

module.exports = ERROR;
